### ISSUE TITLE
Mesh Fixes (Player incorrectly colliding with the ground)

### ISSUE THREAD

**Issue by neo-take-lucy** [UQdeco2800/2021-studio-1#67]
Alright making this an *issue* cause like, yeh dude.

Firstly we know the issue so now it's problem solving
possible methods (?)
- [ ] loading the terrain and then making its own mesh

> what happens when player goes between areas of the mesh?
> yeh maybe gets updated?

- [ ] having some double check between boxes? (this seems like a bandaid tho, whle making a mesh is like... realest)

**Comment by CodePilot58** [comment]
# **Description**
**Feature:** Team 2 - Map fixes and Aesthetic Upgrades, Wall of Death speed change #80 
**Task:** Mesh Fixes (Player incorrectly colliding with the ground) #67 

When loading platforms and floors, a single hitbox will span each collection of these obstacles instead of the many small hitboxes, one for each entity, currently implemented. This will stop the player from 'bouncing' across the map like it currently does.

To enable the platforms and floors to be properly disposed of by `TouchDisposeComponent`, this all-encompassing hitbox will `dispose` of all entities it covers once it is disposed.

This bug is due to Box2d; when the player runs across the boundary between two platforms or floors, their hitbox will be registered to "collide" with what appears to be flat ground.

_note_: I am hoping this will fix another issue we currently have; if the game runs for a while it seems to randomly cause a SEVFAULT from the Box2D code, from the log it can be seen the 'non-class virtual memory' has been filled. Maybe fixing this will stop that memory issue.

**Completion Deadline:** Oct. 5th
 
# **Documentation**
 
# **Members**
- Sam Lucena (@CodePilot58) (Sam Lucena)
